In [4]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [6]:
csv_file_path="/home/ankdesh/explore/prime-google/dataset/MobilenetEdgeTPU/MobilenetEdgeTPU_feasible.csv"

In [7]:
df = pd.read_csv(csv_file_path)

In [16]:
X_train = df.iloc[:, 1:10]
X_train =  X_train.fillna(0)

In [18]:
y_train = df['runtime']
y_train =  y_train.fillna(0)

In [21]:
from sklearn.feature_selection import SelectKBest
from sklearn import feature_selection

print ("Running Select KBest ---")
select = SelectKBest(feature_selection.f_regression, k = 5)
df1 = select.fit_transform(X_train, y_train)
print(df1)

Running Select KBest ---
[[8.000000e+00 6.000000e+00 2.560000e+02 4.000000e+00 4.194304e+06]
 [4.000000e+00 8.000000e+00 6.400000e+01 4.000000e+00 1.310720e+05]
 [6.000000e+00 4.000000e+00 1.600000e+01 1.400000e+01 2.621440e+05]
 ...
 [6.000000e+00 1.000000e+01 6.400000e+01 1.000000e+00 1.048576e+06]
 [8.000000e+00 2.000000e+00 1.280000e+02 1.400000e+01 5.242880e+05]
 [8.000000e+00 8.000000e+00 3.200000e+01 2.000000e+00 3.276800e+04]]


In [26]:
filter = select.get_support()
features = np.array(df.columns)
 
print("All features:")
print(features)
 
print("Selected best 3:")
print(features[filter])

AttributeError: 'numpy.ndarray' object has no attribute 'columns'